Create test examples.
Monnoroch/android-testing pull request #1
Opened 2018-03-05 07:57 UTC by AseevEIDev

2018-03-05 13:20 UTC, Monnoroch requested changes

2018-03-05 13:20 UTC, Monnoroch commented on linters/run/google-java-format.sh
> +    difflines=$(java -jar linters/bin/google-java-format/google-java-format.jar -length 120 --offset 4 "${file}" | diff -u "$file" -)
--offset 2 (т.е. можно убрать)

2018-03-05 14:07 UTC, AseevEIDev commented on linters/run/google-java-format.sh
> +    difflines=$(java -jar linters/bin/google-java-format/google-java-format.jar -length 120 --offset 4 "${file}" | diff -u "$file" -)
На 2 переставить могу, а вот убрать вообще видимо нет, вот что выдает форматтер:
```
The --offset and --length flags must be given an equal number of times.
```
Насколько я понимаю, если есть length, то будь добр offset тоже поставь

2018-03-05 14:09 UTC, Monnoroch commented on linters/run/google-java-format.sh
> +    difflines=$(java -jar linters/bin/google-java-format/google-java-format.jar -length 120 --offset 4 "${file}" | diff -u "$file" -)
Ок. Кстати, протобуфы тоже по 2 пробела надо. Не знаю, что там с линтерами.

2018-03-05 14:14 UTC, AseevEIDev commented on linters/run/google-java-format.sh
> +    difflines=$(java -jar linters/bin/google-java-format/google-java-format.jar -length 120 --offset 4 "${file}" | diff -u "$file" -)
Ну тут протобуфных файлов нет. И ты хочешь все перевести на 2 пробела вместо 4? А зачем?

2018-03-20 12:26 UTC, Monnoroch requested changes

2018-03-20 12:26 UTC, Monnoroch commented on testing/src/main/java/com/testing/user/NameRepository.java
> +   * @param fileReader - for reading string from file content.
Идея примеров -- быть очень простыми. Кажется, что они не требуют документации (важно отметить, что наши тулзы для тестов -- требуют, только примерам она не нужна).

2018-03-20 12:26 UTC, Monnoroch commented on testing/src/main/java/com/testing/user/NameRepository.java
> +   * @param fileReader - for reading string from file content.
Если нельзя выключить линтер только для примеров, хотя бы оставь все доки однострочными.

2018-03-20 12:26 UTC, Monnoroch commented on testing/src/androidTest/java/com/testing/user/UserFragmentTest.java
> +    file =
CreateFileRule

2018-03-20 12:26 UTC, Monnoroch commented on testing/src/main/java/com/testing/user/UserPresenter.java
> +public class UserPresenter {
Этот класс не нужен. Используй NameRepository напрямую.

2018-03-20 12:27 UTC, Monnoroch commented on testing/src/main/java/com/testing/user/NameRepository.java
> +   * @param fileReader - for reading string from file content.
А лучше отключи линтер совсем. Это не продакшн-репозиторий.

2018-03-20 19:48 UTC, AseevEIDev commented on testing/src/androidTest/java/com/testing/user/UserFragmentTest.java
> +    file =
Тут не получится, потому что приложение не имеет доступа к памяти устройства, а только к папке data/data/$PACKAGE_NAME/ и эта папка может иметь разный путь в зависимости от версии Android. 

Я это к тому, что чтобы ее получить - нужно дождаться пока создастся активити и передать это активити в DirRule. А для этого нужно делать отдельный DirRule для этого теста. Так как тест один, то и rule я делать не стал, так как об этом уже и там было много сказано

2018-03-20 19:50 UTC, Monnoroch commented on testing/src/androidTest/java/com/testing/user/UserFragmentTest.java
> +    file =
Т.е. правило из начала статьи бесполезно?

2018-03-20 19:54 UTC, Monnoroch requested changes

2018-03-20 19:54 UTC, Monnoroch commented on testing/src/androidTest/java/com/testing/rules/ActivityTestRule.java
> - * A {@link TestRule} to be used for testing an {@link AppCompatActivity}.
Верни доки либ.

2018-03-20 19:54 UTC, Monnoroch commented on .travis.yml
> -before_install:
Верни линтеры.

2018-03-20 19:54 UTC, AseevEIDev commented on testing/src/androidTest/java/com/testing/user/UserFragmentTest.java
> +    file =
Почему, оно не бесполезно и отлично подходит для юнит тестов, создает файл и используется во многих тестах. Просто к этому тесту его нужно модифицировать:
- передать туда Activity
- взять расположение папки доступной приложению по активити

Я этого делать ради одного теста не стал.

2018-03-20 21:04 UTC, Monnoroch approved these changes

2018-03-20 21:06 UTC, merged